### ISSUE TITLE
etvpn-authenticator allows setting duplicate IP address

### ISSUE THREAD

**Issue by blcetux** [eurotux/etvpn-authenticator#1]
Hi,

We are currently using etvpn-authenticator with an SQLite backend.

We've noticed that the script at `tools/sql/manage_sql_userdb.pl` allows the setup of two different users with the same IP address. Is there any way to configure etvpn-authenticator to prevent this from happening?

Best regards,
Bruno Costa

**Comment by araujorm** [comment]
Hi. Thanks for the input.

We've now added a check to prevent IP duplication on SQL database backends. By default it will be enforced, but should one for some reason need to disable that check, there is also a new option `users allow same fixed ip address` for each SQL backend.

See https://github.com/eurotux/etvpn-authenticator/commit/c58c57e799afcc609c0177dcbd02d33ae6815850
